article_index:
    path:     /
    defaults: { _controller: "WorldCupRussiaBundle:Article:index" }
    methods:  GET

article_indexback:
    path:     /indexback
    defaults: { _controller: "WorldCupRussiaBundle:Article:indexback" }
    methods:  GET

article_show:
    path:     /{id}/show
    defaults: { _controller: "WorldCupRussiaBundle:Article:show" }
    methods:  [GET, POST]

article_showback:
    path:     /{id}/showback
    defaults: { _controller: "WorldCupRussiaBundle:Article:showback" }
    methods:  GET

article_new:
    path:     /new
    defaults: { _controller: "WorldCupRussiaBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /{id}/edit
    defaults: { _controller: "WorldCupRussiaBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /{id}/delete
    defaults: { _controller: "WorldCupRussiaBundle:Article:delete" }
    methods:  DELETE

article_max:
    path:     /max
    defaults: { _controller: "WorldCupRussiaBundle:Article:GetTopCommentedTopic" }
    methods:  GET
