detailsstatistique_index:
    path:     /
    defaults: { _controller: "WorldCupRussiaBundle:DetailsStatistique:index" }
    methods:  GET

detailsstatistique_show:
    path:     /{id}/show
    defaults: { _controller: "WorldCupRussiaBundle:DetailsStatistique:show" }
    methods:  GET

detailsstatistique_new:
    path:     /new
    defaults: { _controller: "WorldCupRussiaBundle:DetailsStatistique:new" }
    methods:  [GET, POST]

detailsstatistique_edit:
    path:     /{id}/edit
    defaults: { _controller: "WorldCupRussiaBundle:DetailsStatistique:edit" }
    methods:  [GET, POST]

detailsstatistique_delete:
    path:     /{id}/delete
    defaults: { _controller: "WorldCupRussiaBundle:DetailsStatistique:delete" }
    methods:  DELETE


detailsstatistique_list:
    path:     /listmatchs
    defaults: { _controller: "WorldCupRussiaBundle:DetailsStatistique:listeMatchs" }
    methods:  GET
