<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    function triArticleParDateDesc()
    {
        $query = $this->getEntityManager()->createQuery("select a from WorldCupRussiaBundle:Article a ORDER BY a.date DESC");

        return $query->getResult();


    }
    function getMaxcommentedArticles()
    {
        $query = $this->getEntityManager()->createQuery("select a,count(a) HIDDEN f from WorldCupRussiaBundle:Article a INNER JOIN WorldCupRussiaBundle:CommentaireArticle c WITH a.id = c.article group by c.article ORDER BY f DESC ")->setMaxResults(3);
        return ($query->getResult());

    }
}
