<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * CategorieBilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieBilletRepository extends \Doctrine\ORM\EntityRepository
{
}
