<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * DetailsStatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsStatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
