<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * EntraineurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntraineurRepository extends \Doctrine\ORM\EntityRepository
{
}
