<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * FeuilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeuilRepository extends \Doctrine\ORM\EntityRepository
{
}
