<?php
/**
 * Created by PhpStorm.
 * User: Mirak
 * Date: 24/04/2018
 * Time: 19:49
 */

namespace WorldCup\RussiaBundle\Repository;

/**
 * FeuilDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class FeuilDetailRepository extends EntityRepository
{

    public function Select($matche,$Feuil)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT u FROM 
      WorldCupRussiaBundle:FeuilDetail u 
            WHERE u.matche = :matche and u.Feuil = :Feuil")->setParameter('matche',$matche)->setParameter('Feuil',$Feuil);
        return $q->getOneOrNullResult();

    }

    public function SelectParFeuil($Feuil)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT u FROM 
      WorldCupRussiaBundle:FeuilDetail u 
            WHERE u.Feuil = :Feuil")->setParameter('Feuil',$Feuil);
        return $q->getResult();

    }
}