<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * FeuilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeuilRepository extends \Doctrine\ORM\EntityRepository
{
    public function Select($Etat)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT u FROM 
      WorldCupRussiaBundle:Feuil u 
            WHERE u.Etat = :Etat")->setParameter('Etat',$Etat);
        return $q->getOneOrNullResult();

    }
}
