<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * MatcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatcheRepository extends \Doctrine\ORM\EntityRepository
{
}
