<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * PronostiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PronostiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
