<?php

namespace WorldCup\RussiaBundle\Repository;

/**
 * StaffeArbitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffeArbitreRepository extends \Doctrine\ORM\EntityRepository
{
}
