world_cup_russia_article:
    resource: "@WorldCupRussiaBundle/Resources/config/routing/article.yml"
    prefix:   /article

world_cup_russia_categorie:
    resource: "@WorldCupRussiaBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

world_cup_russia_commentairearticle:
    resource: "@WorldCupRussiaBundle/Resources/config/routing/commentairearticle.yml"
    prefix:   /commentairearticle

world_cup_russia_arbitre:
        resource: "@WorldCupRussiaBundle/Resources/config/routing/arbitre.yml"
        prefix:   /arbitre
world_cup_russia_stade:
        resource: "@WorldCupRussiaBundle/Resources/config/routing/stade.yml"
        prefix:   /stade
world_cup_russia_ville:
        resource: "@WorldCupRussiaBundle/Resources/config/routing/ville.yml"
        prefix:   /ville

world_cup_russia_feuil:
        resource: "@WorldCupRussiaBundle/Resources/config/routing/feuil.yml"
        prefix:   /feuil

world_cup_russia_feuildetail:
        resource: "@WorldCupRussiaBundle/Resources/config/routing/feuildetail.yml"
        prefix:   /feuildetail

world_cup_russia_homepage:
    path:     /home
    defaults: { _controller: WorldCupRussiaBundle:Default:index }

affichefeuildetail:
    path:     /affichefeuildetail
    defaults: { _controller: WorldCupRussiaBundle:FeuilDetail:affichefeuildetail }

supprimerfeuildetail:
    path:     /supprimerfeuildetail
    defaults: { _controller: WorldCupRussiaBundle:FeuilDetail:supprimerfeuildetail }

ajouterPronostique:
    path:     /ajouterPronostique
    defaults: { _controller: WorldCupRussiaBundle:Pronostique:ajouterPronostique }

world_cup_russia_backpage:
    path:     /back
    defaults: { _controller: WorldCupRussiaBundle:Default:back }

world_cup_russia_matche:
    resource: "@WorldCupRussiaBundle/Resources/config/routing/matche.yml"
    prefix:   /matche

world_cup_russia_detailsstatistique:
        resource: "@WorldCupRussiaBundle/Resources/config/routing/detailsstatistique.yml"
        prefix:   /detailsstatistique